"""initial model

Revision ID: e77856ea6b27
Revises: 3a947eec80a9
Create Date: 2020-11-08 23:15:08.457527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77856ea6b27'
down_revision = '3a947eec80a9'
branch_labels = ()
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION pg_hashids;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), sa.Computed("id_encode(uid, 'U69XD2b3YaIJe2plIN31', 1, 'abcdefghjkmnpqrstuwxyz1234567890')", ), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()::timestamp'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()::timestamp'), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('warehouse',
    sa.Column('whid', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), sa.Computed("id_encode(whid, 'U69XD2b3YaIJe2plIN31', 1, 'abcdefghjkmnpqrstuwxyz1234567890')", ), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()::timestamp'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()::timestamp'), nullable=True),
    sa.Column('repo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('whid')
    )
    op.create_table('workbench',
    sa.Column('wbid', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), sa.Computed("id_encode(wbid, 'U69XD2b3YaIJe2plIN31', 1, 'abcdefghjkmnpqrstuwxyz1234567890')", ), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()::timestamp'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()::timestamp'), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('whid', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['whid'], ['warehouse.whid'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('wbid')
    )
    # ### end Alembic commands ###
    op.execute("ALTER SEQUENCE warehouse_whid_seq RESTART WITH 1000 START WITH 1000 MINVALUE 1000;")
    op.execute("ALTER SEQUENCE workbench_wbid_seq RESTART WITH 1000 START WITH 1000 MINVALUE 1000;")
    op.execute("ALTER SEQUENCE user_uid_seq       RESTART WITH 1000 START WITH 1000 MINVALUE 1000;")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workbench')
    op.drop_table('warehouse')
    op.drop_table('user')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION pg_hashids")
