"""initial setup

Revision ID: cc24348c3806
Revises:
Create Date: 2020-11-01 16:33:09.345765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc24348c3806'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION pg_hashids;")
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), sa.Computed("id_encode(id, 'U69XD2b3YaIJe2plIN31', 1, 'abcdefghjkmnpqrstuwxyz1234567890')", ), nullable=True),
    sa.Column('first_created', sa.DateTime(), server_default=sa.text('now()::timestamp'), nullable=True),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()::timestamp'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), sa.Computed("id_encode(id, 'U69XD2b3YaIJe2plIN31', 1, 'abcdefghjkmnpqrstuwxyz1234567890')", ), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("ALTER SEQUENCE session_id_seq RESTART WITH 1000 START WITH 1000 MINVALUE 1000")
    op.execute("ALTER SEQUENCE user_id_seq    RESTART WITH 1000 START WITH 1000 MINVALUE 1000")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('session')
    # ### end Alembic commands ###
