"""initial user model

Revision ID: a746608f09b1
Revises: e0ad083ae629
Create Date: 2020-12-22 12:37:26.917786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a746608f09b1'
down_revision = 'e0ad083ae629'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_stack',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()::timestamp'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()::timestamp'), nullable=True),
    sa.Column('dsid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('dsid')
    )
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()::timestamp'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()::timestamp'), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), sa.Computed("id_encode(uid, 'U69XD2b3YaIJe2plIN31', 1, 'abcdefghjkmnpqrstuwxyz1234567890')", ), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_data_stack',
    sa.Column('dsid', sa.String(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('dsid', 'uid')
    )
    # ### end Alembic commands ###
    op.execute("ALTER SEQUENCE user_uid_seq RESTART WITH 1000 START WITH 1000 MINVALUE 1000;")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data_stack')
    op.drop_table('user')
    op.drop_table('data_stack')
    # ### end Alembic commands ###
