= DIAAS Architecture

== Entities

=== Data Stack

one full data analytics / intellignece / science setup. Inlcudes the code and infra for ingesting data, storing it somewheree, transforming it, querying it, and generating reports, dashboards and, most importantly, insights. We assume most small and medium sized customers would have exactly one data stack, though larger customers (for example DH) might have one per vertical.

The "current" implementation of a data stack is defined by the files in the `prd` branch of a git repo (whether we created and host the repo or not is not important).

==== notes

- Pushing straight to master is allowed, but fast forward only (so you can't push if your local branch isn't up to date). In the future we should provide a more fine rained way to control this (so PR based work flow)

- checking out the code locally should be a first class citizen. The webapp is an IDE, not "the" UI. We're assuming that our users (at least a significant segment of them) consider this to be an important feature when deciding whether or not to use DIAAS, however we don't actually expect many users to do things via the CLI.

=== User

a human being, someone using the system. Given consultants and agnecies we'll want one person to be able to access multiple organisations or projects.

=== Teams and Roles

We'll need these at some point to provide enough enterprise like permissions and access control. for now we can ignore them.

=== WorkBench

`work bench` our internal name for the "thing" users have in DIAAS. Just an alias for the app itself.  One user has exactly one work bench and can pick which data stack they want to be working on. We don't, for now at least, support working on different data stacks at the same time in, for example, different browsers or sessions.

A WorkBench is a directory containing a bunch of git repos.

Note that a WorkBench is per user, not per session. So mulitple logins from differents devies will access the same set of files.

We could have made the WorkBench's state per-session, but making a logout (or brower crash) cause data lose seems too drastic, and a "recover lost sessoin" UI seems to complicated. this should keep things simple.

there are two important seletors in the UI, one for the current DataStack and one for the current branch in that stack.

== Services

=== BE

flask backend. handles stuff like sessions and logins and calling out to the right DSS. DSS does the actual data stack specific logic (and runs in its own process with its own libraries and modules).

=== FE

This is the IDE, what the user perceives as diaas/caravel. It's a react based FE.

=== libds

The UI works closely with the "api" of the command line tool `ds` (defined in the link:https://gitlab.com/leukosio/libds[`libds` repo]). `libds` is the component that actually loads and runs user code (so any security and resource contraining logic needs to happen here). This way the web part remains an IDE, and the actual per-data-stack logic, like how yaml files translate to extraction operations, can be kept in the dss script/server and run locally when needed (this should also will make testing and development simpler).

Hopefully this has 2 other long term benefits:

1. using the DIAAS tooling from the command line becomes possible. this means we can provide all of our benefits to customers who are very technical and code based.
2. the "api" of the cli is just command names along with json in and json (or yaml) out. Theoretically you coudl swap out the python based ds for something in node or scala.

As we are running the user's pyhton code, which could be malicous, on our servers to collect and load and transform data. even if the code isn't malicious we need some way to protect against infinte loops or crazy resource usage. for now we are more than happy to ignore this problem, but the moment we have 2 users on the same installation we need to think about it. (one solution of course is to not have 2 users on one installation and everyone gets their own infra (snowflake seems to do this), not a bad idea, but probably a bit of over head).

== First Time Setup / Login

We don't have an explicit login/registratino step (for better or for wrose) so every time a new sessin is created we need to check "does this user exist" and if not setup an initial DataStack and WorkBench for them.

When a user creates a new account they get a data stack named whatever their email starts with. and a workbench on that stack and with the production branch checked out.

== Security

we are running random code on our servers. we need something like a server per workbench (maybe per git checkout is a better way to put it). we will run the user's pyhton code, which could be malicous, on our servers to collect and load and transform data. even if the code isn't malicious we need some way to protect against infinte loops or crazy resource usage. for now we are more than happy to ignore this problem, but the moment we have 2 users on the same installation we need to think about it. (one solution of course is to not have 2 users on one installation and everyone gets their own infra (snowflake seems to do this), not a bad idea, but probably a bit of over head).

== Future Improvements

=== Organization

maybe we want to introduce the "organization" as a concept. each org has one set of infra, it can have multiple work benches (though generally i'd have only one) and user mgmt and permissions are al per org. this would certainly make some things simpler.

=== GIT UI

we will have a minimal git tool in the UI. pull from master. commit (which is different from save). push. merge to master. reset hard. no rebase.
