= DIAAS

Data Infrastructure As A Service.

== local develoment

There are scripts in `./ops/lcl/` to run each service, to run them all from the terminal install link:https://duckduckgo.com/?q=tmuxinator&t=newext&atb=v243-1&ia=web[tmuxinator] and run `./ops/lcl/run-in-tmux` (have a look at that file, it's very short, to see how exactly things are started).

developing the data stack code is a workin progress. latest setup
involves jumping into the venv and pip install -e from some directory.


== What's the name again?

Internal code name is DIAAS, but the product is called Caravel (the product name and brnading can change, the internal repo/library name needn't).

== Why not docker-compose?

Since we deploy with docker, it's fair to ask: why don't we use docker for local dev as well?

We had a docker-compose based setup for a while, but file system watchers were hard, enviorment variable management was hard, scripting and tooling so it was convneient to use was hard, and with npm and pyenv the benefit seemed minimal.

pyenv and npm provide very good isolated local environments, and tmux provides a more than good enough (for local dev) way to run all the services including restarting and debugging them as needed.
