#!/bin/bash
set -euo pipefail
git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/leukosio/dev-tools.git /opt/dev-tools/
source /opt/dev-tools/bash/bashrc

set -u; source "${LEUKOS_SH_V1}";

pwd

# Test libds

(
    cd ./libds/
    output-on-failure -- python3 -m venv .venv
    source .venv/bin/activate
    output-on-failure -- pip install -f /opt/downloads/ -U pip wheel
    output-on-failure -- pip install -f /opt/downloads/ -r ./requirements_dev.txt
    output-on-failure -- ../ops/test-libds
)

# Setup node
source "${NVM_DIR}/nvm.sh"
cd "${__root__}/fe/"
nvm use
output-on-failure -- npm ci --cache .npm --prefer-offline

cd "${__root__}"

# Lint
output-on-failure -- python3 -m venv .venv
source .venv/bin/activate
output-on-failure -- pip install -f /opt/downloads/ -U pip wheel
output-on-failure -- pip install -f /opt/downloads/ -r requirements_dev.txt
output-on-failure -- ./ops/do-lint
