#!/bin/bash
set -euo pipefail
if getent group $DIAAS_GID > /dev/null; then
    group="$(getent group $DIAAS_GID | cut -d: -f 1)"
else
    group=diaas
    groupadd --gid $DIAAS_GID $group
fi

if getent passwd $DIAAS_UID > /dev/null; then
    user="$(getent passwd $DIAAS_UID | cut -d: -f 1)"
else
    user=diaas
    useradd -N -M --uid $DIAAS_UID --gid $DIAAS_GID $user
fi

function entry_point {
    exec /sbin/runuser -u $user -g $group -- /usr/bin/env "$@"
}
