version: "3.7"

services:
  be:
    build:
      context: "../../"
      dockerfile: "./ops/lcl/be.Dockerfile"
    environment:
      - DIAAS_BEDB_PGDATABASE
      - DIAAS_BEDB_PGHOST
      - DIAAS_BEDB_PGPASSWORD
      - DIAAS_BEDB_PGPORT
      - DIAAS_BEDB_PGUSER
      - DIAAS_DEPLOYMENT_COMMIT_REF_NAME
      - DIAAS_DEPLOYMENT_COMMIT_SHA
      - DIAAS_DEPLOYMENT_COMMIT_TITLE
      - DIAAS_DEPLOYMENT_ENVIRONMENT
      - DIAAS_ENABLE_SENTRY
      - DIAAS_INSTALL_DIR=/opt/diaas/
      - DIAAS_INTERNAL_API_TOKEN
      - DIAAS_SENTRY_DSN
      - DIAAS_SESSION_COOKIE_IS_SECURE
      - DIAAS_SESSION_SECRET_KEY
      - DIAAS_FILE_STORE=/opt/diaas/file_store/
      - DIAAS_UID
      - DIAAS_GID
      - FLASK_DEBUG
      - FLASK_ENV
    volumes:
      - "be_FILE_STORE:/opt/diaas/file_store/"
      - "../../be/:/opt/diaas/be/"
    ports:
      - "0.0.0.0:8080:8080"
  #    healthcheck:
  #      test: "curl --fail 127.0.0.1:8080/api/_/health"
  #      timeout: 60s
  #      interval: 31s
  #      retries: 2
  bedb:
    build:
      context: "../../"
      dockerfile: "./ops/lcl/bedb.Dockerfile"
    environment:
      - "POSTGRES_PASSWORD=$DIAAS_BEDB_PGPASSWORD"
    ports:
      - "0.0.0.0:$DIAAS_BEDB_PGPORT:5432"
    volumes:
      - "bedb_PGDATA:/var/lib/postgresql/data"
  fe:
    build:
      context: "../../"
      dockerfile: "./ops/lcl/fe.Dockerfile"
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - "../../fe/src:/opt/diaas/fe/src"
      - "../../fe/public:/opt/diaas/fe/public"
      - "../../fe/jsconfig.json:/opt/diaas/fe/jsconfig.json"
    environment:
      - DIAAS_UID
      - DIAAS_GID
      - "REACT_APP_API_BASEURL=http://be:8080/"

volumes:
  bedb_PGDATA: {}
  be_FILE_STORE: {}
