#!/bin/bash
set -u; source "${LEUKOS_SH_V1}"; cd "${__root__}"

export PYTHONPATH="$(cd ./be/src && pwd)"
export PYTHONUNBUFFERED=1
export FLASK_APP=diaas.app
eval "$(./ops/configure-for lcl || echo 'exit 2')"
exec flask "$@"

