#!/bin/bash
set -u; source "${LEUKOS_SH_V1}"; cd "$__root__";

cd fe

eval "$(../ops/configure-for lcl --without-be || echo 'exit 2')"

(cd public && "$NVM_DIR"/nvm-exec node ./docker/build-config-js)

"$NVM_DIR"/nvm-exec npm run start
