#!/bin/bash
set -u; source "${LEUKOS_SH_V1}"; cd "$__root__";

name="lcl-store-clickhouse"
docker volume create "${name}"
docker stop "${name}" || true
docker rm "${name}" || true
docker run -it -v "${name}:/var/lib/clickhouse:rw" --name "${name}" -p 19000:9000 yandex/clickhouse-server

