#!/bin/bash
set -u; source "${LEUKOS_SH_V1}"; cd "$__root__";

eval "$(./ops/configure-for lcl --without-be || echo 'exit 2')"

./ops/fe-build-diaas-js.py > ./fe/public/diaas.js

cd fe && "$NVM_DIR"/nvm-exec npm run start
