name: diaas-lcl
root: '<%= @settings["__root__"] %>'
windows:
  - app:
      layout: even-horizontal
      panes:
        - ./ops/lcl/run-be
        - (cd fe && nvm use && npm ci && ../ops/lcl/run-fe)
  - data:
      layout: even-horizontal
      panes:
        - ./ops/lcl/run-bedb
        - ./ops/lcl/run-lcl-postgres
        - ./ops/lcl/run-lcl-clickhouse
