#!/bin/bash
# -*- sh -*-

commit_sha="$(git -C "${__root__}" rev-parse HEAD)"

if [[ -z "$(git -C "${__root__}" status --porcelain)" ]]; then
    commit_sha="HEAD-${commit_sha}"
fi

timestamp="$(date -u +%Y%m%d-%H%M%S)"
repo="eu.gcr.io/diaas-stg/diaas"
exact_tag="${timestamp}-${commit_sha}"
latest_tag="latest"
