#!/bin/bash
# -*- sh -*-
pushd "${__root__}/"

commit_sha="$(git rev-parse HEAD)"

if [[ -z "$(git status --porcelain)" ]]; then
    commit_sha="HEAD-${commit_sha}"
fi

timestamp="$(date -u +%Y%m%d-%H%M%S)"
repo="eu.gcr.io/diaas-stg/diaas"
exact_tag="${timestamp}-${commit_sha}"
latest_tag="latest"

popd
