#!/usr/bin/env python
from google.cloud import secretmanager
import google.auth
from pprint import pprint  # noqa: F401


def list_secrets(client, project, page_token=None):
    res = client.list_secrets(request={"parent":f"projects/{project}", "page_token": page_token})
    yield from res.secrets
    if res.next_page_token:
        yield from list_secrets(project, res.next_page_token)


def main():
    credentials, project = google.auth.default()
    client = secretmanager.SecretManagerServiceClient(credentials=credentials)
    for s in list_secrets(client, project):
        print(s.name)
        for v in client.list_secret_versions(request={"parent": s.name}):
            print(v.name)


main()
