#!/bin/bash
set -u; source "${LEUKOS_SH_V1}";

cd "${__root__}/be/"
eval "$("${__root__}/ops/configure-for" lcl)"
PYTHONPATH="${__root__}/be/src/:${__root__}/be/tests/" pytest -vvv "$@" "${__root__}/be/tests/"

