#!/bin/bash
set -u; source "${LEUKOS_SH_V1}";

cd "${__root__}/libds/"

declare -a args=("$@")

if [[ "${#args[@]}" -eq 0 ]]; then
   args=("--lf")
fi

find . -name __pycache__ -print0 | xargs --no-run-if-empty -0 rm -r
pytest -vvv "${args[@]}" ./tests/
